#!/usr/bin/env bash
#
# Stand up the AnyBid API on a fresh Debian or Ubuntu machine.
#
#   git clone <this repo> anybid && cd anybid
#   sudo ./scripts/deploy-vm.sh api.anybid.my
#
# Installs Docker if it is missing, writes .env.prod with freshly generated
# secrets if it does not exist, then brings up the stack in
# docker-compose.prod.yml. Safe to re-run: an existing .env.prod is left alone,
# so re-running redeploys rather than rotating your secrets and locking the
# API out of its own database.
#
# Point the DNS A record for your domain at this machine BEFORE running this.
# Caddy orders the TLS certificate on first boot and that fails without DNS.

set -euo pipefail

cd "$(dirname "$0")/.."

if [[ ! -f docker-compose.prod.yml ]]; then
  echo "Run this from a checkout of the AnyBid repository." >&2
  exit 1
fi

DOMAIN="${1:-${API_DOMAIN:-}}"
if [[ -z "$DOMAIN" ]]; then
  read -rp "API domain (e.g. api.anybid.my): " DOMAIN
fi
[[ -n "$DOMAIN" ]] || { echo "An API domain is required." >&2; exit 1; }

# ---------- Docker ----------
if ! command -v docker >/dev/null 2>&1; then
  echo "==> Installing Docker"
  curl -fsSL https://get.docker.com | sh
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "Docker is installed but the compose plugin is missing. Install" >&2
  echo "docker-compose-plugin and re-run." >&2
  exit 1
fi

# ---------- secrets ----------
if [[ -f .env.prod ]]; then
  echo "==> Keeping the existing .env.prod"
else
  echo "==> Writing .env.prod with generated secrets"
  jwt=$(openssl rand -hex 32)
  pgpass=$(openssl rand -hex 24)
  proxysecret=$(openssl rand -hex 32)
  umask 077
  cat > .env.prod <<ENV
# Generated by scripts/deploy-vm.sh. Never commit this file.
API_DOMAIN=$DOMAIN
JWT_SECRET=$jwt
POSTGRES_PASSWORD=$pgpass
DATABASE_URL=postgresql://anybid:$pgpass@postgres:5432/anybid?schema=public
CORS_ORIGINS=https://anybid.my,https://www.anybid.my

# Set this same value as PROXY_SHARED_SECRET in the website's Vercel project.
# It is how the API knows a claimed visitor address came from our own website
# and not from the visitor. Until both sides have it the API ignores the claim
# and every web visitor shares one rate-limit key — safe, but coarse.
PROXY_SHARED_SECRET=$proxysecret

# Cloudflare R2, for listing photos. Until these are filled in the site runs
# normally and the upload endpoint answers 503, so sellers see an honest
# message rather than a broken form. Create a bucket, an R2 API token scoped
# to it, and serve the bucket from a domain you control.
R2_ACCOUNT_ID=
R2_ACCESS_KEY_ID=
R2_SECRET_ACCESS_KEY=
R2_BUCKET=
R2_PUBLIC_BASE_URL=
ENV
fi
chmod 600 .env.prod

# ---------- deploy ----------
echo "==> Building and starting the stack"
docker compose -f docker-compose.prod.yml --env-file .env.prod --profile localdb \
  up -d --build

# ---------- wait for health ----------
echo "==> Waiting for the API to report healthy"
for _ in $(seq 1 60); do
  state=$(docker compose -f docker-compose.prod.yml --env-file .env.prod \
    ps api --format '{{.Health}}' 2>/dev/null || true)
  [[ "$state" == "healthy" ]] && break
  sleep 5
done

if [[ "${state:-}" != "healthy" ]]; then
  echo
  echo "The API did not come up healthy. Logs:" >&2
  docker compose -f docker-compose.prod.yml --env-file .env.prod \
    logs --tail 50 migrate api >&2
  exit 1
fi

cat <<DONE

AnyBid API is up.

  Health   https://$DOMAIN/health
  Logs     docker compose -f docker-compose.prod.yml --env-file .env.prod logs -f api worker

Last step, in Vercel — add these to the anybid project and redeploy:

  NEXT_PUBLIC_API_URL=https://$DOMAIN
  NEXT_PUBLIC_WS_URL=wss://$DOMAIN

The database is empty. To load the demo catalogue, run from a machine that has
Node 22 and this repository, with DATABASE_URL pointing at the database:

  npm install && npm run db:seed
DONE
